#!/usr/bin/env python3
"""
Maqueen Lite · Guide terrain — Phase 1
Builder inspired by abourdim/bit-54-activities + Workshop-DIY v1.2
Single-file HTML, no build step, French-first.
"""
import json, pathlib, html

# ═══════════════════════════════════════════════════════════════════
# CATEGORIES & ACTIVITIES
# ═══════════════════════════════════════════════════════════════════

CATS = [
    {'id': 'start',    'name_fr': 'Démarrer',      'name_en': 'Getting Started', 'name_ar': 'البداية',        'icon': '🌱', 'color': '#40BF4A'},
    {'id': 'officiel', 'name_fr': 'Officiel',      'name_en': 'Official',        'name_ar': 'رسمي',           'icon': '📘', 'color': '#3b82f6'},
    {'id': 'mouvement','name_fr': 'Mouvement',     'name_en': 'Movement',        'name_ar': 'الحركة',          'icon': '🚗', 'color': '#1E90FF'},
    {'id': 'leds',     'name_fr': 'LEDs & Son',    'name_en': 'LEDs & Sound',    'name_ar': 'الأضواء والصوت', 'icon': '💡', 'color': '#E63022'},
    {'id': 'capteurs', 'name_fr': 'Capteurs',      'name_en': 'Sensors',         'name_ar': 'المستشعرات',      'icon': '📡', 'color': '#00A4A6'},
    {'id': 'interact', 'name_fr': 'Interactivité', 'name_en': 'Interactivity',   'name_ar': 'التفاعل',         'icon': '🎮', 'color': '#D400D4'},
    {'id': 'robot',    'name_fr': 'Robotique',     'name_en': 'Robotics',        'name_ar': 'الروبوتات',       'icon': '🤖', 'color': '#9400D3'},
    {'id': 'defis',    'name_fr': 'Défis',         'name_en': 'Challenges',      'name_ar': 'تحديات',          'icon': '🎯', 'color': '#eab308'},
    {'id': 'ia',       'name_fr': 'IA',            'name_en': 'AI',              'name_ar': 'الذكاء الاصطناعي','icon': '🧠', 'color': '#ec4899'},
    {'id': 'parcours', 'name_fr': 'Parcours',      'name_en': 'Learning paths',  'name_ar': 'المسارات',        'icon': '🗺️', 'color': '#14b8a6'},
]

# Phase 1: the 15 official DFRobot wiki examples + 1 Getting Started
# Each activity faithful to https://wiki.dfrobot.com/rob0148-en/

ACTIVITIES = [
    # ─── DÉMARRER ───
    {
        'id': 1, 'cat': 'start', 'stars': 1, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Configuration & calibration',
        'title_en': 'Setup & calibration',
        'title_ar': 'الإعداد والمعايرة',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/22595',
        'objectif_fr': "Installer la bibliothèque MakeCode pour le Maqueen Lite et calibrer les capteurs de suivi de ligne avant la première utilisation.",
        'materiel': ['micro:bit v2', 'Maqueen Lite', 'Câble USB', 'MakeCode', '3× piles AAA'],
        'etapes_fr': [
            "Ouvrir makecode.microbit.org et créer un nouveau projet",
            "Extensions → chercher « maqueen-lite » → ajouter",
            "Placer le Maqueen sur la carte de ligne (ou ruban adhésif noir)",
            "Blocs → Maqueen Lite → calibration des capteurs",
            "Ajuster les vis des capteurs sous le robot jusqu'à lecture stable",
        ],
        'tip_fr': "Sans calibration, le suiveur de ligne zigzague. Prends 2 minutes pour régler.",
        'js': "// Calibration automatique des capteurs de ligne\nmaqueen.calibrate()\nbasic.showString(\"OK\")",
        'py': "# Calibration automatique des capteurs de ligne\nmaqueen.calibrate()\nbasic.show_string(\"OK\")",
        'defis_fr': [
            {'level': 'easy', 'text': "Change le message de confirmation par ton prénom"},
            {'level': 'med',  'text': "Ajoute un bip avec music.playTone(262, 500) après la calibration"},
        ],
    },
    # ─── 15 OFFICIELS ───
    {
        'id': 2, 'cat': 'officiel', 'stars': 1, 'time': '5 min', 'v2': False, 'ai': False,
        'title_fr': "Afficher l'identifiant produit",
        'title_en': 'Display product info',
        'title_ar': 'عرض معلومات المنتج',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20837',
        'objectif_fr': "Afficher l'identifiant du produit (ROB0148-EN) sur la matrice LED du micro:bit.",
        'materiel': ['micro:bit', 'Maqueen Lite', 'MakeCode'],
        'etapes_fr': [
            "Au démarrage, faire défiler le texte « ROB0148-EN »",
            "Téléverser le programme sur le micro:bit",
        ],
        'tip_fr': "Chaque variante régionale a son code : ROB0148-CN (Chine), ROB0148-TW (Taïwan), ROB0148-KR (Corée), ROB148-JP (Japon).",
        'js': "// Affiche l'identifiant produit sur les 25 LEDs\nbasic.showString(\"ROB0148-EN\")",
        'py': "# Affiche l'identifiant produit sur les 25 LEDs\nbasic.show_string(\"ROB0148-EN\")",
        'defis_fr': [
            {'level': 'easy', 'text': "Remplace par ton propre nom"},
            {'level': 'med',  'text': "Ajoute une icône cœur après le texte"},
        ],
    },
    {
        'id': 3, 'cat': 'officiel', 'stars': 1, 'time': '10 min', 'v2': False, 'ai': False,
        'title_fr': 'Clignotement des LEDs',
        'title_en': 'LED light flash',
        'title_ar': 'وميض الأضواء',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20847',
        'objectif_fr': "Faire clignoter les deux LEDs avant du Maqueen (rouges, pilotées par P8 et P12) pour simuler un gyrophare.",
        'materiel': ['Maqueen Lite', 'MakeCode'],
        'etapes_fr': [
            "Allumer les deux LEDs avant",
            "Attendre 500 ms",
            "Éteindre les deux LEDs",
            "Attendre 500 ms",
            "Répéter indéfiniment",
        ],
        'tip_fr': "P8 = LED gauche, P12 = LED droite. Valeur 1 = allumée, 0 = éteinte.",
        'js': "basic.forever(function () {\n    pins.digitalWritePin(DigitalPin.P8, 1)\n    pins.digitalWritePin(DigitalPin.P12, 1)\n    basic.pause(500)\n    pins.digitalWritePin(DigitalPin.P8, 0)\n    pins.digitalWritePin(DigitalPin.P12, 0)\n    basic.pause(500)\n})",
        'py': "def on_forever():\n    pins.digital_write_pin(DigitalPin.P8, 1)\n    pins.digital_write_pin(DigitalPin.P12, 1)\n    basic.pause(500)\n    pins.digital_write_pin(DigitalPin.P8, 0)\n    pins.digital_write_pin(DigitalPin.P12, 0)\n    basic.pause(500)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Alterne gauche / droite au lieu de les allumer ensemble"},
            {'level': 'med',  'text': "Change la vitesse : 100 ms, puis 1000 ms"},
            {'level': 'hard', 'text': "Simule une police : 3 clignotements rapides, puis pause 1 s"},
        ],
    },
    {
        'id': 4, 'cat': 'officiel', 'stars': 2, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Contrôle moteur de base',
        'title_en': 'Motor control basics',
        'title_ar': 'التحكم الأساسي في المحرك',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20849',
        'objectif_fr': "Apprendre à commander les deux moteurs N20 du Maqueen : avancer, reculer, tourner, s'arrêter.",
        'materiel': ['Maqueen Lite', '3× piles AAA', 'MakeCode'],
        'etapes_fr': [
            "Avancer à vitesse 150 pendant 1 seconde",
            "Reculer à vitesse 150 pendant 1 seconde",
            "Tourner à droite (gauche avance, droite recule) 1 seconde",
            "Arrêter les deux moteurs",
        ],
        'tip_fr': "La vitesse va de 0 à 255. En dessous de 50, les moteurs peuvent ne pas bouger.",
        'js': "// Avance\nmaqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)\nbasic.pause(1000)\n// Recule\nmaqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 150)\nbasic.pause(1000)\n// Tourne à droite\nmaqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 150)\nmaqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\nbasic.pause(500)\n// Stop\nmaqueen.motorStop(maqueen.Motors.All)",
        'py': "# Avance\nmaqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 150)\nbasic.pause(1000)\n# Recule\nmaqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 150)\nbasic.pause(1000)\n# Tourne à droite\nmaqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 150)\nmaqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\nbasic.pause(500)\n# Stop\nmaqueen.motor_stop(maqueen.Motors.ALL)",
        'defis_fr': [
            {'level': 'easy', 'text': "Fais un demi-tour (180°) puis reviens au point de départ"},
            {'level': 'med',  'text': "Dessine un carré (4 côtés + 4 tournants à 90°)"},
            {'level': 'hard', 'text': "Dessine un triangle équilatéral (3 côtés + 3 tournants à 120°)"},
        ],
    },
    {
        'id': 5, 'cat': 'officiel', 'stars': 2, 'time': '20 min', 'v2': False, 'ai': False,
        'title_fr': 'Lumière RGB respirante',
        'title_en': 'RGB breathing light',
        'title_ar': 'ضوء RGB المتنفس',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20848',
        'objectif_fr': "Créer un effet « respiration » sur les 4 LEDs RGB d'ambiance — couleur qui s'intensifie puis s'éteint doucement, comme une respiration.",
        'materiel': ['Maqueen Lite', 'MakeCode'],
        'etapes_fr': [
            "Pour chaque intensité de 0 à 255 (montée)",
            "Allumer les 4 LEDs RGB avec cette intensité",
            "Petite pause (10 ms)",
            "Pour chaque intensité de 255 à 0 (descente)",
            "Répéter",
        ],
        'tip_fr': "4 LEDs RGB signifie 16 millions de couleurs. Essaie du bleu, du vert, puis combine.",
        'js': "let i = 0\nbasic.forever(function () {\n    // Respiration montante\n    for (i = 0; i <= 255; i += 5) {\n        maqueen.showColor(neopixel.rgb(i, 0, i / 2))\n        basic.pause(10)\n    }\n    // Respiration descendante\n    for (i = 255; i >= 0; i -= 5) {\n        maqueen.showColor(neopixel.rgb(i, 0, i / 2))\n        basic.pause(10)\n    }\n})",
        'py': "def on_forever():\n    # Respiration montante\n    for i in range(0, 256, 5):\n        maqueen.show_color(neopixel.rgb(i, 0, i // 2))\n        basic.pause(10)\n    # Respiration descendante\n    for i in range(255, -1, -5):\n        maqueen.show_color(neopixel.rgb(i, 0, i // 2))\n        basic.pause(10)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Change la couleur (essaie bleu pur, vert pur, orange)"},
            {'level': 'med',  'text': "Cycle arc-en-ciel complet (rouge → orange → jaune → vert → bleu → violet)"},
            {'level': 'hard', 'text': "Synchronise la respiration avec un son sur le buzzer"},
        ],
    },
    {
        'id': 6, 'cat': 'officiel', 'stars': 2, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Piloter un servomoteur',
        'title_en': 'Drive a servo',
        'title_ar': 'تشغيل المحرك السيرفو',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20838',
        'objectif_fr': "Commander un servomoteur branché sur le port S1 du Maqueen — faire un balayage de 0 à 150 degrés en boucle.",
        'materiel': ['Maqueen Lite', 'Servomoteur 9g', 'MakeCode'],
        'etapes_fr': [
            "Tourner le servo à 0°",
            "Attendre 500 ms",
            "Tourner le servo à 150°",
            "Attendre 500 ms",
            "Répéter",
        ],
        'tip_fr': "Les servos standard vont de 0 à 180°. Le Maqueen recommande 0-150° pour éviter les forcements.",
        'js': "basic.forever(function () {\n    pins.servoWritePin(AnalogPin.P1, 0)\n    basic.pause(500)\n    pins.servoWritePin(AnalogPin.P1, 150)\n    basic.pause(500)\n})",
        'py': "def on_forever():\n    pins.servo_write_pin(AnalogPin.P1, 0)\n    basic.pause(500)\n    pins.servo_write_pin(AnalogPin.P1, 150)\n    basic.pause(500)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Remplace le balayage par 3 positions (0°, 75°, 150°)"},
            {'level': 'med',  'text': "Contrôle le servo avec les boutons A (−10°) et B (+10°)"},
            {'level': 'hard', 'text': "Attache un petit drapeau au servo, programme un « salut » quand on presse A"},
        ],
    },
    {
        'id': 7, 'cat': 'officiel', 'stars': 2, 'time': '20 min', 'v2': False, 'ai': False,
        'title_fr': "Lire la distance ultrason",
        'title_en': 'Read ultrasonic distance',
        'title_ar': 'قراءة المسافة بالموجات فوق الصوتية',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20846',
        'objectif_fr': "Lire la distance en centimètres avec le module ultrasonique SR04 et l'afficher sur la matrice LED du micro:bit.",
        'materiel': ['Maqueen Lite', 'Capteur ultrasons SR04 ou SR04P', 'MakeCode'],
        'etapes_fr': [
            "Connecter le capteur au port ultrasonique du Maqueen",
            "En boucle, lire la distance via maqueen.ultrasonic()",
            "Afficher le nombre sur la matrice LED",
            "Attendre 100 ms pour éviter les réflexions multiples",
        ],
        'tip_fr': "Portée utile : 3 cm à 400 cm. Si le retour est 0 ou < 5, ignore (faux signal).",
        'js': "let distance = 0\nbasic.forever(function () {\n    distance = maqueen.Ultrasonic(PingUnit.Centimeters)\n    if (distance > 5) {\n        basic.showNumber(distance)\n    }\n    basic.pause(100)\n})",
        'py': "def on_forever():\n    distance = maqueen.ultrasonic(PingUnit.CENTIMETERS)\n    if distance > 5:\n        basic.show_number(distance)\n    basic.pause(100)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Allume une LED rouge si la distance < 10 cm"},
            {'level': 'med',  'text': "Joue un son dont la fréquence change avec la distance (sonar)"},
            {'level': 'hard', 'text': "Enregistre la distance minimum vue ces 10 dernières secondes"},
        ],
    },
    {
        'id': 8, 'cat': 'officiel', 'stars': 2, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Lire les capteurs de ligne',
        'title_en': 'Read line-tracking sensors',
        'title_ar': 'قراءة مستشعرات تتبع الخط',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20843',
        'objectif_fr': "Lire l'état des deux capteurs infrarouges de suivi de ligne. Sur ligne noire → 0 ; sur zone blanche → 1.",
        'materiel': ['Maqueen Lite', 'Feuille avec ligne noire', 'MakeCode'],
        'etapes_fr': [
            "Lire le capteur gauche (P13) et le capteur droit (P14)",
            "Afficher la valeur du capteur gauche sur la matrice LED",
            "Ajouter une petite pause",
        ],
        'tip_fr': "Si les deux capteurs lisent toujours 0 ou toujours 1 : recalibre (voir activité 1).",
        'js': "let left = 0\nlet right = 0\nbasic.forever(function () {\n    left = pins.digitalReadPin(DigitalPin.P13)\n    right = pins.digitalReadPin(DigitalPin.P14)\n    basic.showNumber(left)\n    basic.pause(200)\n})",
        'py': "def on_forever():\n    left = pins.digital_read_pin(DigitalPin.P13)\n    right = pins.digital_read_pin(DigitalPin.P14)\n    basic.show_number(left)\n    basic.pause(200)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche G ou D selon quel capteur voit la ligne"},
            {'level': 'med',  'text': "Allume la LED avant correspondante quand chaque capteur voit du noir"},
            {'level': 'hard', 'text': "Combine les 2 capteurs : affiche une flèche (← ↑ → ↓) selon la position de la ligne"},
        ],
    },
    {
        'id': 9, 'cat': 'officiel', 'stars': 3, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Lire les touches infrarouges',
        'title_en': 'Read IR key assignments',
        'title_ar': 'قراءة مفاتيح الأشعة تحت الحمراء',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20845',
        'objectif_fr': "Apprendre à lire les codes des touches d'une télécommande infrarouge NEC, pour les utiliser plus tard.",
        'materiel': ['Maqueen Lite', 'Télécommande IR (kit ROB0148-EN-3)', 'MakeCode'],
        'etapes_fr': [
            "Installer l'extension IR-remote dans MakeCode",
            "Connecter le récepteur IR (par défaut sur P16)",
            "Au déclenchement IR, afficher les 2 derniers chiffres du code",
        ],
        'tip_fr': "Protocole NEC = le plus répandu. Les codes varient selon la télécommande : note-les !",
        'js': "maqueen.IR_Read(IR_Pin.P16)\nmaqueen.IR_Callback(function () {\n    basic.showNumber(maqueen.IR_ReadValue() % 100)\n})",
        'py': "# Note : en MicroPython la gestion IR nécessite une bibliothèque tierce\n# L'approche JavaScript/MakeCode est recommandée pour les télécommandes IR\nmaqueen.ir_read(IR_Pin.P16)\n\ndef on_ir():\n    basic.show_number(maqueen.ir_read_value() % 100)\n\nmaqueen.ir_callback(on_ir)",
        'defis_fr': [
            {'level': 'easy', 'text': "Note les codes des 10 touches numériques"},
            {'level': 'med',  'text': "Affiche une icône différente pour chaque chiffre 0-9"},
            {'level': 'hard', 'text': "Reconstitue le code PIN d'un coffre-fort avec 4 chiffres"},
        ],
    },
    {
        'id': 10, 'cat': 'officiel', 'stars': 3, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Voiture télécommandée IR',
        'title_en': 'IR remote-driven car',
        'title_ar': 'سيارة بجهاز تحكم عن بعد',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en-lb/docs/21449',
        'objectif_fr': "Piloter le Maqueen avec une télécommande infrarouge. Touches 2 = avance, 8 = recul, 4 = gauche, 6 = droite, 5 = stop.",
        'materiel': ['Maqueen Lite', 'Télécommande IR', 'MakeCode'],
        'etapes_fr': [
            "Lire la touche pressée",
            "Selon la touche, faire tourner les moteurs",
            "Touche 5 → stop",
        ],
        'tip_fr': "Les codes touches dépendent de la télécommande. Utilise l'activité 9 pour les noter d'abord.",
        'js': "maqueen.IR_Read(IR_Pin.P16)\nmaqueen.IR_Callback(function () {\n    let key = maqueen.IR_ReadValue()\n    if (key == 24) { // touche 2 : avance\n        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)\n    } else if (key == 82) { // touche 8 : recul\n        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 150)\n    } else if (key == 8) { // touche 4 : gauche\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 150)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 150)\n    } else if (key == 90) { // touche 6 : droite\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n    } else if (key == 28) { // touche 5 : stop\n        maqueen.motorStop(maqueen.Motors.All)\n    }\n})",
        'py': "# JavaScript/MakeCode recommandé pour l'IR — exemple Python équivalent\nmaqueen.ir_read(IR_Pin.P16)\n\ndef on_ir():\n    key = maqueen.ir_read_value()\n    if key == 24:  # touche 2 : avance\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 150)\n    elif key == 82:  # touche 8 : recul\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 150)\n    elif key == 8:  # touche 4 : gauche\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 150)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 150)\n    elif key == 90:  # touche 6 : droite\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n    elif key == 28:  # touche 5 : stop\n        maqueen.motor_stop(maqueen.Motors.ALL)\n\nmaqueen.ir_callback(on_ir)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute un klaxon sur la touche 0"},
            {'level': 'med',  'text': "Touches 1-3 = trois vitesses différentes"},
            {'level': 'hard', 'text': "Mode turbo : appui long sur une touche = vitesse 255"},
        ],
    },
    {
        'id': 11, 'cat': 'officiel', 'stars': 3, 'time': '45 min', 'v2': False, 'ai': False,
        'title_fr': "Évitement d'obstacles",
        'title_en': 'Obstacle avoider',
        'title_ar': 'تجنب العقبات',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20841',
        'objectif_fr': "Le robot avance ; dès qu'un obstacle est détecté à moins de 30 cm, il tourne aléatoirement à gauche ou à droite puis reprend.",
        'materiel': ['Maqueen Lite', 'Capteur ultrasons SR04', 'MakeCode'],
        'etapes_fr': [
            "Avance en permanence",
            "Lire la distance ultrason",
            "Si distance < 30 cm : choisir aléatoirement gauche ou droite, tourner 500 ms",
            "Sinon, continuer d'avancer",
        ],
        'tip_fr': "Utilise Math.randomRange(0, 1) pour un choix aléatoire binaire.",
        'js': "let dist = 0\nlet turn = 0\nbasic.forever(function () {\n    dist = maqueen.Ultrasonic(PingUnit.Centimeters)\n    if (dist > 5 && dist < 30) {\n        maqueen.motorStop(maqueen.Motors.All)\n        turn = Math.randomRange(0, 1)\n        if (turn == 0) {\n            maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 150)\n            maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 150)\n        } else {\n            maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n            maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n        }\n        basic.pause(500)\n    } else {\n        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)\n    }\n})",
        'py': "def on_forever():\n    dist = maqueen.ultrasonic(PingUnit.CENTIMETERS)\n    if 5 < dist < 30:\n        maqueen.motor_stop(maqueen.Motors.ALL)\n        turn = randint(0, 1)\n        if turn == 0:\n            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 150)\n            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 150)\n        else:\n            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n        basic.pause(500)\n    else:\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 150)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Allume une LED rouge quand le robot détecte un obstacle"},
            {'level': 'med',  'text': "Bip progressif : plus l'obstacle est proche, plus le son est aigu"},
            {'level': 'hard', 'text': "Mode « exploration » : compte combien d'obstacles rencontrés en 1 minute"},
        ],
    },
    {
        'id': 12, 'cat': 'officiel', 'stars': 3, 'time': '45 min', 'v2': False, 'ai': False,
        'title_fr': 'Suivi de ligne',
        'title_en': 'Line follower',
        'title_ar': 'متابعة الخط',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en-lb/docs/21447',
        'objectif_fr': "Le robot suit une ligne noire sur fond blanc. Si les deux capteurs voient du noir, il avance ; si un seul capteur voit la ligne, il corrige en tournant.",
        'materiel': ['Maqueen Lite', 'Feuille avec ligne noire (ou ruban adhésif)', 'MakeCode'],
        'etapes_fr': [
            "Lire les deux capteurs (gauche P13, droit P14)",
            "Les deux voient la ligne (0, 0) → avancer",
            "Seul le gauche voit la ligne (0, 1) → tourner à gauche",
            "Seul le droit voit la ligne (1, 0) → tourner à droite",
            "Ni l'un ni l'autre (1, 1) → tourner en rond pour retrouver",
        ],
        'tip_fr': "Valeur 0 = noir, 1 = blanc. Si tu inverses, ton robot « fuit » la ligne au lieu de la suivre.",
        'js': "let left = 0\nlet right = 0\nbasic.forever(function () {\n    left = pins.digitalReadPin(DigitalPin.P13)\n    right = pins.digitalReadPin(DigitalPin.P14)\n    if (left == 0 && right == 0) {\n        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 120)\n    } else if (left == 0 && right == 1) {\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n        maqueen.motorStop(maqueen.Motors.M2)\n    } else if (left == 1 && right == 0) {\n        maqueen.motorStop(maqueen.Motors.M1)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 120)\n    } else {\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 80)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 80)\n    }\n})",
        'py': "def on_forever():\n    left = pins.digital_read_pin(DigitalPin.P13)\n    right = pins.digital_read_pin(DigitalPin.P14)\n    if left == 0 and right == 0:\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 120)\n    elif left == 0 and right == 1:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n        maqueen.motor_stop(maqueen.Motors.M2)\n    elif left == 1 and right == 0:\n        maqueen.motor_stop(maqueen.Motors.M1)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 120)\n    else:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 80)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 80)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Allume les LEDs avant en rouge sur route droite, vertes dans les virages"},
            {'level': 'med',  'text': "Compte les tours avec un marqueur (ligne perpendiculaire tous les X cm)"},
            {'level': 'hard', 'text': "Suivi de ligne proportionnel : plus le capteur dévie, plus le virage est serré"},
        ],
    },
    {
        'id': 13, 'cat': 'officiel', 'stars': 2, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Suivre la lumière',
        'title_en': 'Follow the light',
        'title_ar': 'تتبع الضوء',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20840',
        'objectif_fr': "Le robot avance quand on éclaire les LEDs d'ambiance. Plus la lumière est forte, plus il va vite. Dans le noir, il s'arrête.",
        'materiel': ['Maqueen Lite', 'Lampe torche ou smartphone', 'MakeCode'],
        'etapes_fr': [
            "Lire la valeur du capteur de luminosité (intégré au micro:bit)",
            "Convertir la luminosité (0-255) en vitesse moteur",
            "Faire avancer le robot à cette vitesse",
        ],
        'tip_fr': "La luminosité se lit via input.lightLevel() — elle va de 0 (noir) à 255 (plein soleil).",
        'js': "let light = 0\nbasic.forever(function () {\n    light = input.lightLevel()\n    if (light > 50) {\n        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, light)\n    } else {\n        maqueen.motorStop(maqueen.Motors.All)\n    }\n})",
        'py': "def on_forever():\n    light = input.light_level()\n    if light > 50:\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, light)\n    else:\n        maqueen.motor_stop(maqueen.Motors.ALL)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche la luminosité en barre sur la matrice LED"},
            {'level': 'med',  'text': "Inverse : le robot fuit la lumière (animal nocturne)"},
            {'level': 'hard', 'text': "Phototropisme : tourne pour trouver la direction la plus lumineuse"},
        ],
    },
    {
        'id': 14, 'cat': 'officiel', 'stars': 3, 'time': '45 min', 'v2': False, 'ai': False,
        'title_fr': 'Télécommande gamepad sans fil',
        'title_en': 'Wireless gamepad control',
        'title_ar': 'التحكم اللاسلكي بجهاز الألعاب',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20839',
        'objectif_fr': "Piloter le Maqueen avec un deuxième micro:bit (ou le micro:Gamepad DFRobot) via radio. Joystick ou boutons.",
        'materiel': ['2× micro:bit', 'Maqueen Lite', 'micro:Gamepad (optionnel)'],
        'etapes_fr': [
            "Télécommande : au démarrage, rejoindre le groupe radio 1",
            "Télécommande : envoyer « F » (forward), « B » (back), « L », « R », « S »",
            "Robot : mêmé groupe radio 1, lire les messages reçus",
            "Robot : selon le message, faire tourner les moteurs",
        ],
        'tip_fr': "Les deux micro:bit doivent être sur le même groupe radio (radio.setGroup).",
        'js': "// ─── Télécommande (micro:bit 1) ───\nradio.setGroup(1)\ninput.onButtonPressed(Button.A, function () { radio.sendString(\"L\") })\ninput.onButtonPressed(Button.B, function () { radio.sendString(\"R\") })\ninput.onGesture(Gesture.Shake, function () { radio.sendString(\"S\") })\n// forward/back sur inclinaison\nbasic.forever(function () {\n    if (input.acceleration(Dimension.Y) < -300) radio.sendString(\"F\")\n    else if (input.acceleration(Dimension.Y) > 300) radio.sendString(\"B\")\n})\n\n// ─── Robot (micro:bit 2) ───\nradio.setGroup(1)\nradio.onReceivedString(function (cmd) {\n    if (cmd == \"F\") maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)\n    else if (cmd == \"B\") maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 150)\n    else if (cmd == \"L\") {\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 150)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 150)\n    } else if (cmd == \"R\") {\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n    } else if (cmd == \"S\") maqueen.motorStop(maqueen.Motors.All)\n})",
        'py': "# ─── Télécommande (micro:bit 1) ───\nradio.set_group(1)\n\ndef on_button_a():\n    radio.send_string(\"L\")\ninput.on_button_pressed(Button.A, on_button_a)\n\ndef on_button_b():\n    radio.send_string(\"R\")\ninput.on_button_pressed(Button.B, on_button_b)\n\n# ─── Robot (micro:bit 2) ───\nradio.set_group(1)\n\ndef on_received(cmd):\n    if cmd == \"F\":\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 150)\n    elif cmd == \"B\":\n        maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 150)\n    elif cmd == \"L\":\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 150)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 150)\n    elif cmd == \"R\":\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n    elif cmd == \"S\":\n        maqueen.motor_stop(maqueen.Motors.ALL)\n\nradio.on_received_string(on_received)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute un klaxon (touche A+B = buzzer)"},
            {'level': 'med',  'text': "Vitesse proportionnelle à l'inclinaison du micro:bit"},
            {'level': 'hard', 'text': "Mode course : 2 robots, chacun son groupe radio, chronomètre sur la télécommande"},
        ],
    },
    {
        'id': 15, 'cat': 'officiel', 'stars': 3, 'time': '45 min', 'v2': False, 'ai': False,
        'title_fr': 'Télécommande IR — conduite complète',
        'title_en': 'IR remote — full driving',
        'title_ar': 'تحكم IR كامل',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en-lb/docs/21449',
        'objectif_fr': "Version avancée du contrôle IR : conduite progressive, klaxon, couleurs LEDs, modes de vitesse. Tout depuis la télécommande.",
        'materiel': ['Maqueen Lite', 'Télécommande IR (kit ROB0148-EN-3)', 'MakeCode'],
        'etapes_fr': [
            "Touches directionnelles 2/4/6/8 = conduite",
            "Touche 5 = stop d'urgence",
            "Touche 0 = klaxon",
            "Touches 1-3 = 3 vitesses préréglées",
            "Touches 7-9 = 3 couleurs d'ambiance",
        ],
        'tip_fr': "Stocke la vitesse dans une variable globale — tu la changeras avec 1/2/3 et tu l'utiliseras dans toutes les touches de conduite.",
        'js': "let speed = 150\nmaqueen.IR_Read(IR_Pin.P16)\nmaqueen.IR_Callback(function () {\n    let key = maqueen.IR_ReadValue()\n    if (key == 12) speed = 80          // touche 1 : lent\n    else if (key == 24) maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, speed)   // 2 : avance\n    else if (key == 94) speed = 150     // 3 : normal\n    else if (key == 8) {                // 4 : gauche\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, speed)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, speed)\n    } else if (key == 28) maqueen.motorStop(maqueen.Motors.All)  // 5 : stop\n    else if (key == 90) {               // 6 : droite\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, speed)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, speed)\n    } else if (key == 66) maqueen.showColor(neopixel.colors(NeoPixelColors.Red))      // 7 : rouge\n    else if (key == 82) maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, speed)  // 8 : recul\n    else if (key == 74) maqueen.showColor(neopixel.colors(NeoPixelColors.Blue))       // 9 : bleu\n    else if (key == 22) music.playTone(523, 200)  // 0 : klaxon\n})",
        'py': "speed = 150\nmaqueen.ir_read(IR_Pin.P16)\n\ndef on_ir():\n    global speed\n    key = maqueen.ir_read_value()\n    if key == 12: speed = 80\n    elif key == 24: maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, speed)\n    elif key == 94: speed = 150\n    elif key == 8:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, speed)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, speed)\n    elif key == 28: maqueen.motor_stop(maqueen.Motors.ALL)\n    elif key == 90:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, speed)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, speed)\n    elif key == 66: maqueen.show_color(neopixel.colors(NeoPixelColors.RED))\n    elif key == 82: maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, speed)\n    elif key == 74: maqueen.show_color(neopixel.colors(NeoPixelColors.BLUE))\n    elif key == 22: music.play_tone(523, 200)\n\nmaqueen.ir_callback(on_ir)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute un mode « discothèque » avec 1 touche dédiée (couleurs aléatoires)"},
            {'level': 'med',  'text': "Mode turbo temporaire : touche # → vitesse 255 pendant 3 secondes"},
            {'level': 'hard', 'text': "Mémoire de trajet : touche * enregistre les 30 dernières commandes et les rejoue"},
        ],
    },
    {
        'id': 16, 'cat': 'officiel', 'stars': 1, 'time': '5 min', 'v2': False, 'ai': False,
        'title_fr': 'Référence du Maqueen',
        'title_en': 'Maqueen reference',
        'title_ar': 'مرجع Maqueen',
        'official': True, 'wiki': 'https://wiki.dfrobot.com/rob0148-en/docs/20836',
        'objectif_fr': "Fiche technique : ports, broches, capteurs, limites de chaque composant. À avoir sous la main quand tu construis.",
        'materiel': ['Ce guide ! 📚'],
        'etapes_fr': [
            "Alimentation : 3,5–5 V (3× AAA ou Li-ion 3,7 V)",
            "Moteurs : 2× N20 métal, pilotés en PWM",
            "LEDs avant : P8 (gauche), P12 (droite), 0/1 on/off",
            "LEDs RGB ambiance : 4 NeoPixel, 16M couleurs, via lib Maqueen",
            "Capteurs ligne : P13 (gauche), P14 (droite), 0 = noir, 1 = blanc",
            "Ultrason : port dédié SR04/SR04P (5V)",
            "Servo : S1 + S2 sur broches AnalogPin",
            "IR : récepteur NEC sur P16",
            "Extension I²C : 5V, pour module supplémentaire",
            "Broches dispo : P0, P1, P2 (Gravity)",
        ],
        'tip_fr': "Imprime cette page et colle-la à côté de ton poste de travail. Tu t'y réfèreras des centaines de fois.",
        'js': "// Cette activité est une référence — pas de code à exécuter.\n// Voir les activités ci-dessus pour des exemples sur chaque composant.",
        'py': "# Cette activité est une référence — pas de code à exécuter.\n# Voir les activités ci-dessus pour des exemples sur chaque composant.",
        'defis_fr': [],
    },
]

print(f"Defined {len(ACTIVITIES)} activities in {len(CATS)} categories")
print(f"Phase 1 targets: Getting Started (1) + Officiel (15) = 16 activities")

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == '--check':
        sys.exit(0)
