"""Phase 2 activities — Simple tier. ~30 activities covering Movement, LEDs/Sound, Sensors, Interactivity.
Each activity is creative but achievable by ages 8-12 with the Maqueen + micro:bit."""

PHASE2 = [
    # ═══ MOUVEMENT (7) ═══ ids 17-23
    {
        'id': 17, 'cat': 'mouvement', 'stars': 1, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Danse en carré', 'title_en': 'Square dance', 'title_ar': 'رقصة المربع',
        'official': False,
        'objectif_fr': "Le robot dessine un carré parfait : avance, tourne à droite, 4 fois de suite. Retour au point de départ.",
        'materiel': ['Maqueen Lite', 'Espace dégagé ~50cm²'],
        'etapes_fr': [
            "Répéter 4 fois :",
            "Avancer 1 seconde",
            "Tourner à droite 500 ms",
            "Arrêter à la fin",
        ],
        'tip_fr': "Si ton carré n'est pas fermé, ajuste la durée du virage (400ms à 600ms selon tes piles).",
        'js': "for (let i = 0; i < 4; i++) {\n    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 120)\n    basic.pause(1000)\n    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 120)\n    basic.pause(500)\n}\nmaqueen.motorStop(maqueen.Motors.All)",
        'py': "for i in range(4):\n    maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 120)\n    basic.pause(1000)\n    maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n    maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 120)\n    basic.pause(500)\nmaqueen.motor_stop(maqueen.Motors.ALL)",
        'defis_fr': [
            {'level': 'easy', 'text': "Fais un triangle (3 côtés, tourne de 120°)"},
            {'level': 'med',  'text': "Dessine un hexagone (6 côtés, 60°)"},
            {'level': 'hard', 'text': "Dessine un octogone, puis reviens en arrière sur la même trajectoire"},
        ],
    },
    {
        'id': 18, 'cat': 'mouvement', 'stars': 2, 'time': '20 min', 'v2': False, 'ai': False,
        'title_fr': 'Contrôle de vitesse', 'title_en': 'Speed control', 'title_ar': 'التحكم في السرعة',
        'official': False,
        'objectif_fr': "Utiliser les boutons A et B pour changer la vitesse du robot : A ralentit, B accélère.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Démarrer à vitesse 100",
            "Si bouton A pressé : vitesse -30 (minimum 0)",
            "Si bouton B pressé : vitesse +30 (maximum 255)",
            "Avancer à cette vitesse en permanence",
        ],
        'tip_fr': "Utilise Math.max et Math.min pour garder la vitesse entre 0 et 255.",
        'js': "let speed = 100\ninput.onButtonPressed(Button.A, function () {\n    speed = Math.max(0, speed - 30)\n    basic.showNumber(speed)\n})\ninput.onButtonPressed(Button.B, function () {\n    speed = Math.min(255, speed + 30)\n    basic.showNumber(speed)\n})\nbasic.forever(function () {\n    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, speed)\n})",
        'py': "speed = 100\n\ndef on_button_a():\n    global speed\n    speed = max(0, speed - 30)\n    basic.show_number(speed)\ninput.on_button_pressed(Button.A, on_button_a)\n\ndef on_button_b():\n    global speed\n    speed = min(255, speed + 30)\n    basic.show_number(speed)\ninput.on_button_pressed(Button.B, on_button_b)\n\ndef on_forever():\n    maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, speed)\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche la vitesse sous forme de barre (0-9 LEDs allumées)"},
            {'level': 'med',  'text': "Bouton A+B = reset à 100"},
        ],
    },
    {
        'id': 19, 'cat': 'mouvement', 'stars': 2, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Pilotage par inclinaison', 'title_en': 'Tilt-drive', 'title_ar': 'التحكم بالإمالة',
        'official': False,
        'objectif_fr': "Piloter le Maqueen en inclinant un second micro:bit comme une télécommande. L'accéléromètre détecte l'inclinaison et envoie par radio.",
        'materiel': ['2× micro:bit', 'Maqueen Lite'],
        'etapes_fr': [
            "Télécommande : en boucle, lire l'accélération X et Y",
            "Envoyer les valeurs par radio",
            "Robot : écouter la radio, convertir en vitesses moteur",
            "Pencher = avancer, pencher l'inverse = reculer, gauche/droite = tourner",
        ],
        'tip_fr': "L'accélération va de -1023 à +1023. Divise par 5 pour obtenir une vitesse raisonnable.",
        'js': "// ─── Télécommande ───\nradio.setGroup(7)\nbasic.forever(function () {\n    let x = input.acceleration(Dimension.X)\n    let y = input.acceleration(Dimension.Y)\n    radio.sendValue(\"x\", x)\n    radio.sendValue(\"y\", y)\n    basic.pause(100)\n})\n\n// ─── Robot ───\nradio.setGroup(7)\nlet tiltX = 0\nlet tiltY = 0\nradio.onReceivedValue(function (name, value) {\n    if (name == \"x\") tiltX = value\n    if (name == \"y\") tiltY = value\n    let fwd = -tiltY / 5\n    let turn = tiltX / 5\n    let left = Math.max(-200, Math.min(200, fwd + turn))\n    let right = Math.max(-200, Math.min(200, fwd - turn))\n    maqueen.motorRun(maqueen.Motors.M1, left > 0 ? maqueen.Dir.CW : maqueen.Dir.CCW, Math.abs(left))\n    maqueen.motorRun(maqueen.Motors.M2, right > 0 ? maqueen.Dir.CW : maqueen.Dir.CCW, Math.abs(right))\n})",
        'py': "# ─── Télécommande ───\nradio.set_group(7)\ndef on_forever():\n    x = input.acceleration(Dimension.X)\n    y = input.acceleration(Dimension.Y)\n    radio.send_value(\"x\", x)\n    radio.send_value(\"y\", y)\n    basic.pause(100)\nbasic.forever(on_forever)\n\n# ─── Robot ───\nradio.set_group(7)\ntilt_x = 0\ntilt_y = 0\n\ndef on_received(name, value):\n    global tilt_x, tilt_y\n    if name == \"x\": tilt_x = value\n    if name == \"y\": tilt_y = value\n    fwd = -tilt_y // 5\n    turn = tilt_x // 5\n    left = max(-200, min(200, fwd + turn))\n    right = max(-200, min(200, fwd - turn))\n    maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW if left > 0 else maqueen.Dir.CCW, abs(left))\n    maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW if right > 0 else maqueen.Dir.CCW, abs(right))\n\nradio.on_received_value(on_received)",
        'defis_fr': [
            {'level': 'med',  'text': "Affiche une flèche sur la matrice LED indiquant la direction"},
            {'level': 'hard', 'text': "Mode « nitro » : secoue la télécommande = 3 secondes à vitesse max"},
        ],
    },
    {
        'id': 20, 'cat': 'mouvement', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Course de vitesse chronométrée', 'title_en': 'Timed speed run', 'title_ar': 'سباق السرعة الموقوت',
        'official': False,
        'objectif_fr': "Chronomètre combien de temps le robot met pour parcourir une distance donnée. Bip au départ, bip à l'arrivée.",
        'materiel': ['Maqueen Lite', 'Ruban 2 mètres', 'Chronomètre (optionnel)'],
        'etapes_fr': [
            "Au bouton A : démarrer, noter l'heure",
            "Avancer pendant 3 secondes à vitesse max",
            "S'arrêter, calculer le temps écoulé",
            "Afficher le temps en millisecondes",
        ],
        'tip_fr': "input.runningTime() donne les millisecondes depuis le démarrage.",
        'js': "let start = 0\ninput.onButtonPressed(Button.A, function () {\n    music.playTone(660, 200)\n    start = input.runningTime()\n    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)\n    basic.pause(3000)\n    maqueen.motorStop(maqueen.Motors.All)\n    music.playTone(880, 400)\n    basic.showNumber(input.runningTime() - start)\n})",
        'py': "start = 0\n\ndef on_button_a():\n    global start\n    music.play_tone(660, 200)\n    start = input.running_time()\n    maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)\n    basic.pause(3000)\n    maqueen.motor_stop(maqueen.Motors.ALL)\n    music.play_tone(880, 400)\n    basic.show_number(input.running_time() - start)\n\ninput.on_button_pressed(Button.A, on_button_a)",
        'defis_fr': [
            {'level': 'easy', 'text': "Compte à rebours 3-2-1 avant le départ"},
            {'level': 'med',  'text': "Enregistre le meilleur temps de la session"},
            {'level': 'hard', 'text': "Organise un tournoi à 4 robots, classement auto"},
        ],
    },
    {
        'id': 21, 'cat': 'mouvement', 'stars': 2, 'time': '20 min', 'v2': False, 'ai': False,
        'title_fr': 'Marche aléatoire', 'title_en': 'Random walk', 'title_ar': 'المشي العشوائي',
        'official': False,
        'objectif_fr': "Le robot se déplace de manière imprévisible : il avance une durée aléatoire, tourne d'un angle aléatoire, recommence. Comme une mouche qui explore.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "En boucle : avancer pendant une durée aléatoire (500-2000 ms)",
            "Choisir aléatoirement gauche ou droite",
            "Tourner pendant une durée aléatoire (200-600 ms)",
            "Répéter",
        ],
        'tip_fr': "Math.randomRange(a, b) retourne un entier entre a et b inclus.",
        'js': "basic.forever(function () {\n    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)\n    basic.pause(Math.randomRange(500, 2000))\n    if (Math.randomRange(0, 1) == 0) {\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 120)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 120)\n    } else {\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 120)\n    }\n    basic.pause(Math.randomRange(200, 600))\n})",
        'py': "from random import randint\n\ndef on_forever():\n    maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 150)\n    basic.pause(randint(500, 2000))\n    if randint(0, 1) == 0:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 120)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 120)\n    else:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 120)\n    basic.pause(randint(200, 600))\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Allume une LED d'une couleur aléatoire à chaque changement de direction"},
            {'level': 'med',  'text': "Le robot joue une note différente à chaque mouvement"},
        ],
    },
    {
        'id': 22, 'cat': 'mouvement', 'stars': 3, 'time': '45 min', 'v2': False, 'ai': False,
        'title_fr': 'Dessin Spirographe', 'title_en': 'Spirograph drawing', 'title_ar': 'رسم سبيروجراف',
        'official': False,
        'objectif_fr': "Attacher un feutre au Maqueen et le faire dessiner des spirales et des fleurs sur une grande feuille de papier.",
        'materiel': ['Maqueen Lite', 'Feutre à bout fin', 'Scotch', 'Grande feuille de papier'],
        'etapes_fr': [
            "Scotcher le feutre centré sous le Maqueen (trou de vis disponible)",
            "Faire avancer avec une légère différence de vitesse entre les deux moteurs",
            "Répéter pendant 20 secondes",
            "Admirer la spirale !",
        ],
        'tip_fr': "Petite différence = grande spirale. Grande différence = petits cercles.",
        'js': "// Crée une spirale en gardant un moteur légèrement plus rapide que l'autre\nmaqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 130)\nmaqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 100)\nbasic.pause(20000)\nmaqueen.motorStop(maqueen.Motors.All)\nmusic.playTone(523, 400)",
        'py': "# Crée une spirale en gardant un moteur légèrement plus rapide que l'autre\nmaqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 130)\nmaqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 100)\nbasic.pause(20000)\nmaqueen.motor_stop(maqueen.Motors.ALL)\nmusic.play_tone(523, 400)",
        'defis_fr': [
            {'level': 'easy', 'text': "Change les vitesses toutes les 5 secondes pour varier le dessin"},
            {'level': 'med',  'text': "Mode « fleur » : alterne 3s en avant, 3s en arrière, 10 fois"},
            {'level': 'hard', 'text': "Programme les initiales de ton prénom en enchaînant des segments et virages"},
        ],
    },
    {
        'id': 23, 'cat': 'mouvement', 'stars': 3, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Parcours enregistré et rejoué', 'title_en': 'Record & replay', 'title_ar': 'التسجيل والإعادة',
        'official': False,
        'objectif_fr': "Enregistrer une séquence de mouvements (via les boutons), puis la rejouer à l'identique. Base pour une chorégraphie de robot.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Mode enregistrement (bouton A) : chaque bouton (haut=avance, A+B=stop...) enregistre son temps et sa direction",
            "Mode rejouer (bouton B) : relire la liste et refaire chaque action",
            "Effacer : shake pour vider le tableau",
        ],
        'tip_fr': "Pour simplifier, enregistre juste 5 actions prédéfinies (F/B/L/R/S) avec leur durée.",
        'js': "let history: string[] = []\nlet recording = false\nlet lastTime = 0\ninput.onButtonPressed(Button.A, function () {\n    recording = true\n    history = []\n    lastTime = input.runningTime()\n    basic.showString(\"R\")\n})\ninput.onButtonPressed(Button.B, function () {\n    recording = false\n    basic.showString(\"P\")\n    for (let cmd of history) {\n        let parts = cmd.split(\":\")\n        basic.pause(parseInt(parts[1]))\n        if (parts[0] == \"F\") maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 150)\n        else if (parts[0] == \"S\") maqueen.motorStop(maqueen.Motors.All)\n    }\n})\n// À ajouter : boutons ou inclinaison pour pousser dans history pendant le recording",
        'py': "history = []\nrecording = False\nlast_time = 0\n\ndef on_button_a():\n    global recording, history, last_time\n    recording = True\n    history = []\n    last_time = input.running_time()\n    basic.show_string(\"R\")\ninput.on_button_pressed(Button.A, on_button_a)\n\ndef on_button_b():\n    global recording\n    recording = False\n    basic.show_string(\"P\")\n    for cmd in history:\n        parts = cmd.split(\":\")\n        basic.pause(int(parts[1]))\n        if parts[0] == \"F\":\n            maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 150)\n        elif parts[0] == \"S\":\n            maqueen.motor_stop(maqueen.Motors.ALL)\ninput.on_button_pressed(Button.B, on_button_b)",
        'defis_fr': [
            {'level': 'hard', 'text': "Sauvegarde la séquence en flash pour qu'elle survive au redémarrage"},
        ],
    },

    # ═══ LEDS & SON (8) ═══ ids 24-31
    {
        'id': 24, 'cat': 'leds', 'stars': 1, 'time': '10 min', 'v2': False, 'ai': False,
        'title_fr': 'Arc-en-ciel RGB', 'title_en': 'RGB rainbow', 'title_ar': 'قوس قزح',
        'official': False,
        'objectif_fr': "Faire défiler un arc-en-ciel complet sur les 4 LEDs RGB d'ambiance du Maqueen.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Cycler à travers les teintes (hue) de 0 à 255",
            "Afficher la couleur sur les 4 LEDs",
            "Petite pause pour rendre visible",
            "Répéter",
        ],
        'tip_fr': "La librairie neopixel gère les teintes HSV. Plus naturel qu'en RGB pour les arcs-en-ciel.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nlet hue = 0\nbasic.forever(function () {\n    hue = (hue + 2) % 360\n    strip.showColor(neopixel.hsl(hue, 99, 50))\n    basic.pause(30)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\nhue = 0\n\ndef on_forever():\n    global hue\n    hue = (hue + 2) % 360\n    strip.show_color(neopixel.hsl(hue, 99, 50))\n    basic.pause(30)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Change la vitesse de défilement (10ms = rapide, 200ms = lent)"},
            {'level': 'med',  'text': "Chaque LED a une teinte décalée de 90° = effet gradient"},
        ],
    },
    {
        'id': 25, 'cat': 'leds', 'stars': 1, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Clignotant de voiture', 'title_en': 'Car turn signal', 'title_ar': 'إشارة الدوران',
        'official': False,
        'objectif_fr': "Simuler les clignotants d'une voiture : bouton A = clignotant gauche, B = droit, A+B = warning (les deux).",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Au bouton A : alterner la LED gauche (P8) toutes les 500ms",
            "Au bouton B : alterner la LED droite (P12)",
            "Au bouton A+B : les deux clignotent ensemble",
        ],
        'tip_fr': "Utilise une variable globale pour savoir quel mode est actif, et une boucle forever pour le clignotement.",
        'js': "let mode = 0  // 0=off, 1=gauche, 2=droit, 3=warning\ninput.onButtonPressed(Button.A, () => mode = 1)\ninput.onButtonPressed(Button.B, () => mode = 2)\ninput.onButtonPressed(Button.AB, () => mode = 3)\ninput.onGesture(Gesture.Shake, () => mode = 0)\nbasic.forever(function () {\n    if (mode == 1 || mode == 3) pins.digitalWritePin(DigitalPin.P8, 1)\n    if (mode == 2 || mode == 3) pins.digitalWritePin(DigitalPin.P12, 1)\n    basic.pause(400)\n    pins.digitalWritePin(DigitalPin.P8, 0)\n    pins.digitalWritePin(DigitalPin.P12, 0)\n    basic.pause(400)\n})",
        'py': "mode = 0\n\ndef on_a():\n    global mode; mode = 1\ninput.on_button_pressed(Button.A, on_a)\n\ndef on_b():\n    global mode; mode = 2\ninput.on_button_pressed(Button.B, on_b)\n\ndef on_ab():\n    global mode; mode = 3\ninput.on_button_pressed(Button.AB, on_ab)\n\ndef on_shake():\n    global mode; mode = 0\ninput.on_gesture(Gesture.SHAKE, on_shake)\n\ndef on_forever():\n    if mode == 1 or mode == 3: pins.digital_write_pin(DigitalPin.P8, 1)\n    if mode == 2 or mode == 3: pins.digital_write_pin(DigitalPin.P12, 1)\n    basic.pause(400)\n    pins.digital_write_pin(DigitalPin.P8, 0)\n    pins.digital_write_pin(DigitalPin.P12, 0)\n    basic.pause(400)\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute un bip discret à chaque clignotement"},
            {'level': 'med',  'text': "Les RGB d'ambiance clignotent orange en même temps"},
        ],
    },
    {
        'id': 26, 'cat': 'leds', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Lampe torche adaptative', 'title_en': 'Smart flashlight', 'title_ar': 'مصباح يدوي ذكي',
        'official': False,
        'objectif_fr': "Le robot devient une lampe qui s'allume automatiquement quand il fait sombre et s'éteint quand il fait jour.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Lire la luminosité en permanence",
            "Si luminosité < 80 : LEDs avant allumées + RGB blanche brillante",
            "Sinon : LEDs éteintes",
            "Petite pause pour éviter le clignotement",
        ],
        'tip_fr': "Ajoute une marge (hysteresis) entre allumer et éteindre pour éviter les tremblements.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nlet on = false\nbasic.forever(function () {\n    let light = input.lightLevel()\n    if (!on && light < 60) {\n        on = true\n        pins.digitalWritePin(DigitalPin.P8, 1)\n        pins.digitalWritePin(DigitalPin.P12, 1)\n        strip.showColor(neopixel.colors(NeoPixelColors.White))\n    } else if (on && light > 100) {\n        on = false\n        pins.digitalWritePin(DigitalPin.P8, 0)\n        pins.digitalWritePin(DigitalPin.P12, 0)\n        strip.clear()\n    strip.show()\n    }\n    basic.pause(200)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\non = False\n\ndef on_forever():\n    global on\n    light = input.light_level()\n    if not on and light < 60:\n        on = True\n        pins.digital_write_pin(DigitalPin.P8, 1)\n        pins.digital_write_pin(DigitalPin.P12, 1)\n        strip.show_color(neopixel.colors(NeoPixelColors.WHITE))\n    elif on and light > 100:\n        on = False\n        pins.digital_write_pin(DigitalPin.P8, 0)\n        pins.digital_write_pin(DigitalPin.P12, 0)\n        strip.clear()\n    strip.show()\n    basic.pause(200)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'med',  'text': "Affiche la luminosité en bar-graphe sur la matrice LED"},
            {'level': 'hard', 'text': "Ajoute un mode « veilleuse » : s'allume rouge doux dans la pénombre"},
        ],
    },
    {
        'id': 27, 'cat': 'leds', 'stars': 2, 'time': '20 min', 'v2': False, 'ai': False,
        'title_fr': 'Piano portable', 'title_en': 'Portable piano', 'title_ar': 'بيانو محمول',
        'official': False,
        'objectif_fr': "Jouer 8 notes avec les boutons et l'inclinaison du micro:bit. Do, ré, mi, fa, sol, la, si, do aigu.",
        'materiel': ['micro:bit', 'Maqueen Lite (optionnel, pour le haut-parleur)'],
        'etapes_fr': [
            "Bouton A : joue DO",
            "Bouton B : joue MI",
            "Bouton A+B : joue SOL",
            "Incline à gauche : joue RÉ, à droite : FA, en avant : LA, en arrière : SI",
            "Secoue : joue DO aigu",
        ],
        'tip_fr': "music.playTone(262, 400) = Do pendant 400ms. Les fréquences : 262, 294, 330, 349, 392, 440, 494, 523.",
        'js': "input.onButtonPressed(Button.A, () => music.playTone(262, 300))      // DO\ninput.onButtonPressed(Button.B, () => music.playTone(330, 300))      // MI\ninput.onButtonPressed(Button.AB, () => music.playTone(392, 300))     // SOL\ninput.onGesture(Gesture.TiltLeft, () => music.playTone(294, 300))    // RE\ninput.onGesture(Gesture.TiltRight, () => music.playTone(349, 300))   // FA\ninput.onGesture(Gesture.LogoUp, () => music.playTone(440, 300))      // LA\ninput.onGesture(Gesture.LogoDown, () => music.playTone(494, 300))    // SI\ninput.onGesture(Gesture.Shake, () => music.playTone(523, 300))       // DO+",
        'py': "def on_a(): music.play_tone(262, 300)\ninput.on_button_pressed(Button.A, on_a)\ndef on_b(): music.play_tone(330, 300)\ninput.on_button_pressed(Button.B, on_b)\ndef on_ab(): music.play_tone(392, 300)\ninput.on_button_pressed(Button.AB, on_ab)\ndef on_tl(): music.play_tone(294, 300)\ninput.on_gesture(Gesture.TILT_LEFT, on_tl)\ndef on_tr(): music.play_tone(349, 300)\ninput.on_gesture(Gesture.TILT_RIGHT, on_tr)\ndef on_up(): music.play_tone(440, 300)\ninput.on_gesture(Gesture.LOGO_UP, on_up)\ndef on_dn(): music.play_tone(494, 300)\ninput.on_gesture(Gesture.LOGO_DOWN, on_dn)\ndef on_sh(): music.play_tone(523, 300)\ninput.on_gesture(Gesture.SHAKE, on_sh)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche la note jouée sur la matrice LED (C, D, E...)"},
            {'level': 'med',  'text': "Programme une mélodie connue (ex: Au clair de la lune) sur une seule touche"},
            {'level': 'hard', 'text': "Mode enregistrement : mémorise 20 notes puis les rejoue"},
        ],
    },
    {
        'id': 28, 'cat': 'leds', 'stars': 2, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Disco bot', 'title_en': 'Disco bot', 'title_ar': 'روبوت الديسكو',
        'official': False,
        'objectif_fr': "Le robot devient une boule disco : couleurs qui clignotent au rythme, moteurs qui tournent, buzzer qui joue une mélodie.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Boucle principale : choisir couleur RGB aléatoire",
            "Afficher sur les 4 LEDs + LEDs avant à 50% random",
            "Jouer une note aléatoire",
            "Moteurs : pivoter dans une direction aléatoire 200ms",
            "Répéter",
        ],
        'tip_fr': "neopixel.rgb(r,g,b) accepte des valeurs 0-255 pour chaque canal.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nlet notes = [262, 294, 330, 349, 392, 440, 494, 523]\nbasic.forever(function () {\n    strip.showColor(neopixel.rgb(Math.randomRange(0, 255), Math.randomRange(0, 255), Math.randomRange(0, 255)))\n    pins.digitalWritePin(DigitalPin.P8, Math.randomRange(0, 1))\n    pins.digitalWritePin(DigitalPin.P12, Math.randomRange(0, 1))\n    music.playTone(notes[Math.randomRange(0, 7)], 150)\n    let spin = Math.randomRange(0, 1) == 0 ? maqueen.Dir.CW : maqueen.Dir.CCW\n    maqueen.motorRun(maqueen.Motors.M1, spin, 120)\n    maqueen.motorRun(maqueen.Motors.M2, spin == maqueen.Dir.CW ? maqueen.Dir.CCW : maqueen.Dir.CW, 120)\n    basic.pause(200)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\nfrom random import randint\nnotes = [262, 294, 330, 349, 392, 440, 494, 523]\n\ndef on_forever():\n    strip.show_color(neopixel.rgb(randint(0,255), randint(0,255), randint(0,255)))\n    pins.digital_write_pin(DigitalPin.P8, randint(0,1))\n    pins.digital_write_pin(DigitalPin.P12, randint(0,1))\n    music.play_tone(notes[randint(0,7)], 150)\n    if randint(0,1) == 0:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 120)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 120)\n    else:\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 120)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 120)\n    basic.pause(200)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Bouton A = mode lent (500ms entre les changements)"},
            {'level': 'med',  'text': "Programme une vraie mélodie (pas aléatoire) en boucle"},
        ],
    },
    {
        'id': 29, 'cat': 'leds', 'stars': 2, 'time': '20 min', 'v2': True, 'ai': False,
        'title_fr': 'VU-mètre audio', 'title_en': 'Audio VU-meter', 'title_ar': 'مقياس الصوت',
        'official': False,
        'objectif_fr': "Utiliser le microphone intégré au micro:bit v2 pour mesurer le volume ambiant. Le robot s'illumine plus fort quand tu cries.",
        'materiel': ['micro:bit V2', 'Maqueen Lite'],
        'etapes_fr': [
            "Lire le niveau sonore (input.soundLevel, 0-255)",
            "Convertir en couleur : silence = bleu, modéré = vert, fort = rouge",
            "Afficher sur les 4 LEDs RGB",
            "Répéter",
        ],
        'tip_fr': "Le capteur réagit vite ! Ajoute une moyenne mobile pour un rendu plus doux.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nbasic.forever(function () {\n    let level = input.soundLevel()\n    if (level < 80) strip.showColor(neopixel.rgb(0, 0, 150))\n    else if (level < 160) strip.showColor(neopixel.rgb(0, 200, 0))\n    else strip.showColor(neopixel.rgb(255, 50, 0))\n    basic.pause(50)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\ndef on_forever():\n    level = input.sound_level()\n    if level < 80:\n        strip.show_color(neopixel.rgb(0, 0, 150))\n    elif level < 160:\n        strip.show_color(neopixel.rgb(0, 200, 0))\n    else:\n        strip.show_color(neopixel.rgb(255, 50, 0))\n    basic.pause(50)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche un bar-graphe sur la matrice LED en fonction du volume"},
            {'level': 'med',  'text': "Le robot avance quand tu cries, s'arrête quand c'est silencieux"},
        ],
    },
    {
        'id': 30, 'cat': 'leds', 'stars': 3, 'time': '45 min', 'v2': False, 'ai': False,
        'title_fr': 'Feu de cheminée animé', 'title_en': 'Animated fireplace', 'title_ar': 'موقد مُحرَّك',
        'official': False,
        'objectif_fr': "Faire danser une animation de flammes sur les 4 LEDs RGB : rouge/orange/jaune qui scintillent comme un vrai feu.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Générer 4 couleurs aléatoires dans la palette rouge-orange-jaune",
            "Chaque LED clignote indépendamment à intensité variable",
            "Tempo rapide (50-100 ms) pour effet naturel",
            "Répéter",
        ],
        'tip_fr': "Restreins le bleu à 0, le vert à 0-50, le rouge à 150-255 pour rester dans les tons chauds.",
        'js': "basic.forever(function () {\n    for (let i = 0; i < 4; i++) {\n        let r = Math.randomRange(180, 255)\n        let g = Math.randomRange(0, 80)\n        maqueen.setPixelColor(i, neopixel.rgb(r, g, 0))\n    }\n    basic.pause(Math.randomRange(50, 120))\n})",
        'py': "from random import randint\n\ndef on_forever():\n    for i in range(4):\n        r = randint(180, 255)\n        g = randint(0, 80)\n        maqueen.set_pixel_color(i, neopixel.rgb(r, g, 0))\n    basic.pause(randint(50, 120))\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute un léger crépitement audio avec des notes aléatoires très courtes"},
            {'level': 'med',  'text': "Mode « feu bleu » avec cyan/bleu/violet"},
        ],
    },
    {
        'id': 31, 'cat': 'leds', 'stars': 1, 'time': '10 min', 'v2': False, 'ai': False,
        'title_fr': 'Sirène de police', 'title_en': 'Police siren', 'title_ar': 'صافرة الشرطة',
        'official': False,
        'objectif_fr': "Alterner rapidement bleu et rouge sur les LEDs + sirène bi-tonale sur le buzzer. Full cop car mode.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Afficher bleu sur les 4 LEDs",
            "Jouer une note grave",
            "Afficher rouge sur les 4 LEDs",
            "Jouer une note aiguë",
            "Répéter",
        ],
        'tip_fr': "Les vraies sirènes oscillent entre ~600Hz et ~900Hz.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nbasic.forever(function () {\n    strip.showColor(neopixel.colors(NeoPixelColors.Blue))\n    music.playTone(600, 300)\n    strip.showColor(neopixel.colors(NeoPixelColors.Red))\n    music.playTone(900, 300)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\ndef on_forever():\n    strip.show_color(neopixel.colors(NeoPixelColors.BLUE))\n    music.play_tone(600, 300)\n    strip.show_color(neopixel.colors(NeoPixelColors.RED))\n    music.play_tone(900, 300)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute un effet oscillation de fréquence plus progressif"},
            {'level': 'med',  'text': "Bouton A active/désactive la sirène"},
        ],
    },

    # ═══ CAPTEURS (8) ═══ ids 32-39
    {
        'id': 32, 'cat': 'capteurs', 'stars': 1, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Thermomètre LED', 'title_en': 'LED thermometer', 'title_ar': 'مقياس حرارة LED',
        'official': False,
        'objectif_fr': "Utiliser le capteur de température du micro:bit. Afficher la valeur en °C et colorer les LEDs : bleu/froid, vert/normal, rouge/chaud.",
        'materiel': ['micro:bit', 'Maqueen Lite'],
        'etapes_fr': [
            "Lire la température (input.temperature(), °C)",
            "Afficher le nombre sur la matrice LED",
            "Bleu si < 18, vert si 18-25, rouge si > 25",
            "Répéter toutes les secondes",
        ],
        'tip_fr': "La température du micro:bit est légèrement plus haute que la vraie temp ambiante (puce chaude). Décale de -3°C pour être réaliste.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nbasic.forever(function () {\n    let t = input.temperature() - 3\n    basic.showNumber(t)\n    if (t < 18) strip.showColor(neopixel.colors(NeoPixelColors.Blue))\n    else if (t < 25) strip.showColor(neopixel.colors(NeoPixelColors.Green))\n    else strip.showColor(neopixel.colors(NeoPixelColors.Red))\n    basic.pause(2000)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\ndef on_forever():\n    t = input.temperature() - 3\n    basic.show_number(t)\n    if t < 18:\n        strip.show_color(neopixel.colors(NeoPixelColors.BLUE))\n    elif t < 25:\n        strip.show_color(neopixel.colors(NeoPixelColors.GREEN))\n    else:\n        strip.show_color(neopixel.colors(NeoPixelColors.RED))\n    basic.pause(2000)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche « COLD » / « OK » / « HOT » au lieu du nombre"},
            {'level': 'med',  'text': "Sonne une alarme si la température dépasse 30°C"},
            {'level': 'hard', 'text': "Enregistre min et max de la session, les affiche sur bouton A"},
        ],
    },
    {
        'id': 33, 'cat': 'capteurs', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Boussole LED', 'title_en': 'LED compass', 'title_ar': 'بوصلة LED',
        'official': False,
        'objectif_fr': "Afficher une flèche sur la matrice LED qui pointe toujours vers le Nord magnétique.",
        'materiel': ['micro:bit'],
        'etapes_fr': [
            "Calibrer la boussole au premier démarrage (bouger le micro:bit en 8)",
            "Lire l'angle magnétique (0-360°)",
            "Convertir en une des 8 directions (N/NE/E/SE/S/SW/W/NW)",
            "Afficher une flèche correspondante",
        ],
        'tip_fr': "input.compassHeading() calibre automatiquement la première fois. C'est normal de voir « TILT TO FILL SCREEN ».",
        'js': "basic.forever(function () {\n    let h = input.compassHeading()\n    if (h < 23 || h >= 338) basic.showArrow(ArrowNames.North)\n    else if (h < 68) basic.showArrow(ArrowNames.NorthEast)\n    else if (h < 113) basic.showArrow(ArrowNames.East)\n    else if (h < 158) basic.showArrow(ArrowNames.SouthEast)\n    else if (h < 203) basic.showArrow(ArrowNames.South)\n    else if (h < 248) basic.showArrow(ArrowNames.SouthWest)\n    else if (h < 293) basic.showArrow(ArrowNames.West)\n    else basic.showArrow(ArrowNames.NorthWest)\n})",
        'py': "def on_forever():\n    h = input.compass_heading()\n    if h < 23 or h >= 338: basic.show_arrow(ArrowNames.NORTH)\n    elif h < 68: basic.show_arrow(ArrowNames.NORTH_EAST)\n    elif h < 113: basic.show_arrow(ArrowNames.EAST)\n    elif h < 158: basic.show_arrow(ArrowNames.SOUTH_EAST)\n    elif h < 203: basic.show_arrow(ArrowNames.SOUTH)\n    elif h < 248: basic.show_arrow(ArrowNames.SOUTH_WEST)\n    elif h < 293: basic.show_arrow(ArrowNames.WEST)\n    else: basic.show_arrow(ArrowNames.NORTH_WEST)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'med',  'text': "Fais le robot tourner jusqu'à pointer vers le Nord automatiquement"},
            {'level': 'hard', 'text': "Navigation : « va 50 pas au Nord, puis 30 pas à l'Est »"},
        ],
    },
    {
        'id': 34, 'cat': 'capteurs', 'stars': 2, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Télémètre sonore', 'title_en': 'Sound telemeter', 'title_ar': 'مقياس الصوت',
        'official': False,
        'objectif_fr': "Le robot émet un son dont la fréquence change avec la distance d'un obstacle devant lui. Proche = aigu, loin = grave. Comme un sonar.",
        'materiel': ['Maqueen Lite', 'Capteur ultrasons SR04'],
        'etapes_fr': [
            "En boucle : mesurer la distance ultrason",
            "Convertir la distance en fréquence : 200Hz (loin) à 2000Hz (proche)",
            "Jouer cette note pendant 100ms",
            "Pause de 100ms pour respirer",
        ],
        'tip_fr': "Utilise Math.map pour convertir une plage en une autre. distance 0-100 → fréquence 2000-200.",
        'js': "basic.forever(function () {\n    let d = maqueen.Ultrasonic()\n    if (d > 3 && d < 100) {\n        let freq = Math.map(d, 3, 100, 2000, 200)\n        music.playTone(freq, 100)\n    }\n    basic.pause(100)\n})",
        'py': "def on_forever():\n    d = maqueen.ultrasonic()\n    if 3 < d < 100:\n        freq = int(2000 - (d - 3) * (2000 - 200) / (100 - 3))\n        music.play_tone(freq, 100)\n    basic.pause(100)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Allume une LED rouge si distance < 10cm"},
            {'level': 'med',  'text': "Bip plus rapide (moins de pause) quand proche"},
        ],
    },
    {
        'id': 35, 'cat': 'capteurs', 'stars': 2, 'time': '20 min', 'v2': False, 'ai': False,
        'title_fr': 'Niveau à bulle', 'title_en': 'Bubble level', 'title_ar': 'ميزان ماء',
        'official': False,
        'objectif_fr': "Utiliser l'accéléromètre pour transformer le micro:bit en niveau à bulle : une LED centrale s'allume quand c'est à l'horizontale.",
        'materiel': ['micro:bit'],
        'etapes_fr': [
            "Lire accélération X et Y",
            "Si |X| < 50 et |Y| < 50 : allumer LED centrale + bip de succès",
            "Sinon : allumer une LED qui indique la direction d'inclinaison",
        ],
        'tip_fr': "Pour montrer la direction, convertis X et Y en coordonnées 0-4 sur la matrice 5x5.",
        'js': "basic.forever(function () {\n    basic.clearScreen()\n    let x = input.acceleration(Dimension.X)\n    let y = input.acceleration(Dimension.Y)\n    if (Math.abs(x) < 50 && Math.abs(y) < 50) {\n        led.plot(2, 2)\n    } else {\n        let cx = Math.max(0, Math.min(4, 2 + Math.floor(x / 250)))\n        let cy = Math.max(0, Math.min(4, 2 + Math.floor(y / 250)))\n        led.plot(cx, cy)\n    }\n    basic.pause(50)\n})",
        'py': "def on_forever():\n    basic.clear_screen()\n    x = input.acceleration(Dimension.X)\n    y = input.acceleration(Dimension.Y)\n    if abs(x) < 50 and abs(y) < 50:\n        led.plot(2, 2)\n    else:\n        cx = max(0, min(4, 2 + x // 250))\n        cy = max(0, min(4, 2 + y // 250))\n        led.plot(cx, cy)\n    basic.pause(50)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'easy', 'text': "Joue un son de validation à chaque fois que tu trouves l'horizontale"},
            {'level': 'med',  'text': "Affiche une croix verte quand à l'horizontale, rouge sinon"},
        ],
    },
    {
        'id': 36, 'cat': 'capteurs', 'stars': 2, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Détecteur de chute', 'title_en': 'Fall detector', 'title_ar': 'كاشف السقوط',
        'official': False,
        'objectif_fr': "Le robot déclenche une alarme si on le secoue ou s'il tombe. Utilise Gesture.Shake et FreeFall.",
        'materiel': ['micro:bit', 'Maqueen Lite'],
        'etapes_fr': [
            "À la chute libre (Gesture.FreeFall) : alarme ROUGE + buzzer strident",
            "Au choc (Gesture.Shake) : afficher ⚠️ + bip",
            "Bouton A : remise à zéro, message calme",
        ],
        'tip_fr': "FreeFall détecte quand l'accélération tend vers 0 (chute libre).",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\ninput.onGesture(Gesture.FreeFall, function () {\n    basic.showIcon(IconNames.Skull)\n    for (let i = 0; i < 5; i++) {\n        strip.showColor(neopixel.colors(NeoPixelColors.Red))\n        music.playTone(880, 100)\n        strip.clear()\n    strip.show()\n        basic.pause(80)\n    }\n})\ninput.onGesture(Gesture.Shake, function () {\n    basic.showIcon(IconNames.Silly)\n    music.playTone(440, 200)\n})\ninput.onButtonPressed(Button.A, function () {\n    basic.showIcon(IconNames.Happy)\n    strip.showColor(neopixel.colors(NeoPixelColors.Green))\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\ndef on_ff():\n    basic.show_icon(IconNames.SKULL)\n    for i in range(5):\n        strip.show_color(neopixel.colors(NeoPixelColors.RED))\n        music.play_tone(880, 100)\n        strip.clear()\n    strip.show()\n        basic.pause(80)\ninput.on_gesture(Gesture.FREE_FALL, on_ff)\n\ndef on_shake():\n    basic.show_icon(IconNames.SILLY)\n    music.play_tone(440, 200)\ninput.on_gesture(Gesture.SHAKE, on_shake)\n\ndef on_a():\n    basic.show_icon(IconNames.HAPPY)\n    strip.show_color(neopixel.colors(NeoPixelColors.GREEN))\ninput.on_button_pressed(Button.A, on_a)",
        'defis_fr': [
            {'level': 'med',  'text': "Compte le nombre de chutes dans la session"},
            {'level': 'hard', 'text': "Envoie une alerte radio à un autre micro:bit en cas de chute"},
        ],
    },
    {
        'id': 37, 'cat': 'capteurs', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Compteur de pas', 'title_en': 'Step counter', 'title_ar': 'عداد الخطوات',
        'official': False,
        'objectif_fr': "Attache le micro:bit à ta chaussure. Il compte tes pas en détectant les pics d'accélération.",
        'materiel': ['micro:bit', 'Élastique ou scotch'],
        'etapes_fr': [
            "En boucle : lire la magnitude de l'accélération",
            "Si accélération > seuil (1800) : incrémenter le compteur",
            "Attendre un délai (500ms) pour éviter de compter plusieurs fois un même pas",
            "Bouton A : afficher le total",
        ],
        'tip_fr': "input.acceleration(Dimension.Strength) donne la magnitude (toujours ≥ 0).",
        'js': "let steps = 0\nbasic.forever(function () {\n    let mag = input.acceleration(Dimension.Strength)\n    if (mag > 1800) {\n        steps++\n        basic.showLeds(`\n            . . . . .\n            . # . # .\n            . . . . .\n            # . . . #\n            . # # # .`)\n        basic.pause(500)\n    }\n})\ninput.onButtonPressed(Button.A, () => basic.showNumber(steps))",
        'py': "steps = 0\n\ndef on_forever():\n    global steps\n    mag = input.acceleration(Dimension.STRENGTH)\n    if mag > 1800:\n        steps += 1\n        basic.show_leds(\"\"\"\n            . . . . .\n            . # . # .\n            . . . . .\n            # . . . #\n            . # # # .\n            \"\"\")\n        basic.pause(500)\n\nbasic.forever(on_forever)\n\ndef on_a():\n    basic.show_number(steps)\ninput.on_button_pressed(Button.A, on_a)",
        'defis_fr': [
            {'level': 'easy', 'text': "Fais-lui jouer un son tous les 10 pas"},
            {'level': 'med',  'text': "Remise à zéro avec le shake"},
        ],
    },
    {
        'id': 38, 'cat': 'capteurs', 'stars': 3, 'time': '40 min', 'v2': False, 'ai': False,
        'title_fr': 'Détecteur de mouvement (alarme)', 'title_en': 'Motion alarm', 'title_ar': 'منبه الحركة',
        'official': False,
        'objectif_fr': "Installer le Maqueen en mode sentinelle : s'il détecte du mouvement ultrason, sirène d'alarme + flash des LEDs rouges.",
        'materiel': ['Maqueen Lite', 'Capteur ultrasons SR04'],
        'etapes_fr': [
            "Lire la distance de base (baseline)",
            "En boucle : comparer la distance courante à la baseline",
            "Si différence > 20 cm : alarme",
            "Touche A : réinitialiser la baseline (après avoir déplacé)",
        ],
        'tip_fr': "Laisse 5 secondes après le démarrage avant de lire la baseline pour laisser le temps de placer le robot.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nlet baseline = 0\nbasic.pause(5000)\nbaseline = maqueen.Ultrasonic()\ninput.onButtonPressed(Button.A, () => baseline = maqueen.Ultrasonic())\nbasic.forever(function () {\n    let d = maqueen.Ultrasonic()\n    if (d > 3 && Math.abs(d - baseline) > 20) {\n        for (let i = 0; i < 10; i++) {\n            strip.showColor(neopixel.colors(NeoPixelColors.Red))\n            music.playTone(880, 80)\n            strip.clear()\n    strip.show()\n            basic.pause(80)\n        }\n    }\n    basic.pause(100)\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\nbaseline = 0\nbasic.pause(5000)\nbaseline = maqueen.ultrasonic()\n\ndef on_a():\n    global baseline\n    baseline = maqueen.ultrasonic()\ninput.on_button_pressed(Button.A, on_a)\n\ndef on_forever():\n    d = maqueen.ultrasonic()\n    if d > 3 and abs(d - baseline) > 20:\n        for i in range(10):\n            strip.show_color(neopixel.colors(NeoPixelColors.RED))\n            music.play_tone(880, 80)\n            strip.clear()\n    strip.show()\n            basic.pause(80)\n    basic.pause(100)\n\nbasic.forever(on_forever)",
        'defis_fr': [
            {'level': 'med',  'text': "Comptabilise le nombre d'intrusions et l'affiche"},
            {'level': 'hard', 'text': "Envoie un message radio à un autre micro:bit « surveillance »"},
        ],
    },
    {
        'id': 39, 'cat': 'capteurs', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Enregistreur de lumière', 'title_en': 'Light logger', 'title_ar': 'مسجل الضوء',
        'official': False,
        'objectif_fr': "Promène le Maqueen dans la maison. Il enregistre le niveau de lumière à chaque appui de bouton, puis affiche un graphique.",
        'materiel': ['Maqueen Lite'],
        'etapes_fr': [
            "Bouton A : enregistrer la luminosité actuelle dans un tableau",
            "Bouton B : afficher toutes les valeurs en bar-graph sur la matrice LED",
            "Shake : effacer la liste",
        ],
        'tip_fr': "La matrice LED 5x5 peut afficher 5 mesures côte-à-côte, chacune avec une hauteur de 0 à 5 LEDs.",
        'js': "let values: number[] = []\ninput.onButtonPressed(Button.A, function () {\n    values.push(input.lightLevel())\n    basic.showNumber(values.length)\n})\ninput.onButtonPressed(Button.B, function () {\n    basic.clearScreen()\n    let show = values.slice(-5)\n    for (let i = 0; i < show.length; i++) {\n        let height = Math.round(show[i] / 51)  // 255/5\n        for (let y = 0; y < height; y++) {\n            led.plot(i, 4 - y)\n        }\n    }\n})\ninput.onGesture(Gesture.Shake, function () { values = []; basic.showIcon(IconNames.No) })",
        'py': "values = []\n\ndef on_a():\n    values.append(input.light_level())\n    basic.show_number(len(values))\ninput.on_button_pressed(Button.A, on_a)\n\ndef on_b():\n    basic.clear_screen()\n    show = values[-5:]\n    for i, v in enumerate(show):\n        height = v // 51\n        for y in range(height):\n            led.plot(i, 4 - y)\ninput.on_button_pressed(Button.B, on_b)\n\ndef on_shake():\n    global values\n    values = []\n    basic.show_icon(IconNames.NO)\ninput.on_gesture(Gesture.SHAKE, on_shake)",
        'defis_fr': [
            {'level': 'med',  'text': "Sauvegarde les valeurs et leur temps d'enregistrement"},
            {'level': 'hard', 'text': "Envoie les données par radio vers un autre micro:bit qui les affiche défilantes"},
        ],
    },

    # ═══ INTERACTIVITÉ (6) ═══ ids 40-45
    {
        'id': 40, 'cat': 'interact', 'stars': 1, 'time': '15 min', 'v2': False, 'ai': False,
        'title_fr': 'Magic 8-ball', 'title_en': 'Magic 8-ball', 'title_ar': 'كرة السحر 8',
        'official': False,
        'objectif_fr': "Pose une question oui/non au Maqueen, secoue-le, il te répond par une icône mystérieuse. Oracle garanti !",
        'materiel': ['micro:bit', 'Maqueen Lite'],
        'etapes_fr': [
            "Au Shake : choisir aléatoirement une réponse parmi 8 options",
            "Afficher l'icône/texte correspondant",
            "Ajouter une couleur d'ambiance théâtrale",
        ],
        'tip_fr': "Les 8 réponses classiques : OUI, NON, PEUT-ÊTRE, BIEN SÛR, JAMAIS, DEMANDE PLUS TARD, ASTRE FAVORABLE, INCERTAIN.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nlet answers = [\"OUI\", \"NON\", \"PTET\", \"SUR\", \"NON!\", \"???\", \"OK\", \"HMM\"]\ninput.onGesture(Gesture.Shake, function () {\n    strip.showColor(neopixel.colors(NeoPixelColors.Purple))\n    basic.pause(500)\n    let pick = Math.randomRange(0, 7)\n    basic.showString(answers[pick])\n    strip.clear()\n    strip.show()\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\nfrom random import randint\nanswers = [\"OUI\", \"NON\", \"PTET\", \"SUR\", \"NON!\", \"???\", \"OK\", \"HMM\"]\n\ndef on_shake():\n    strip.show_color(neopixel.colors(NeoPixelColors.PURPLE))\n    basic.pause(500)\n    pick = randint(0, 7)\n    basic.show_string(answers[pick])\n    strip.clear()\n    strip.show()\ninput.on_gesture(Gesture.SHAKE, on_shake)",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute une petite mélodie mystique avant la réponse"},
            {'level': 'med',  'text': "Après 3 questions, propose une prophétie longue (texte défilant)"},
        ],
    },
    {
        'id': 41, 'cat': 'interact', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Dé numérique', 'title_en': 'Digital dice', 'title_ar': 'نرد رقمي',
        'official': False,
        'objectif_fr': "Au shake, le micro:bit affiche un nombre aléatoire de 1 à 6, comme un vrai dé. Avec animation et son.",
        'materiel': ['micro:bit'],
        'etapes_fr': [
            "Au Shake : animation « roulement » (nombres défilants rapides)",
            "Tirage aléatoire entre 1 et 6",
            "Afficher le résultat",
            "Bip de validation",
        ],
        'tip_fr': "Affiche 5-6 nombres aléatoires très vite pour simuler le roulement avant le résultat final.",
        'js': "input.onGesture(Gesture.Shake, function () {\n    for (let i = 0; i < 6; i++) {\n        basic.showNumber(Math.randomRange(1, 6))\n        basic.pause(60)\n    }\n    let result = Math.randomRange(1, 6)\n    basic.showNumber(result)\n    music.playTone(659, 200)\n    music.playTone(784, 300)\n})",
        'py': "from random import randint\n\ndef on_shake():\n    for i in range(6):\n        basic.show_number(randint(1, 6))\n        basic.pause(60)\n    result = randint(1, 6)\n    basic.show_number(result)\n    music.play_tone(659, 200)\n    music.play_tone(784, 300)\n\ninput.on_gesture(Gesture.SHAKE, on_shake)",
        'defis_fr': [
            {'level': 'easy', 'text': "Affiche les pips (points) du dé avec des LEDs au lieu du nombre"},
            {'level': 'med',  'text': "Mode 2 dés : somme et affichage"},
            {'level': 'hard', 'text': "Dé à 20 faces pour les jeux de rôle"},
        ],
    },
    {
        'id': 42, 'cat': 'interact', 'stars': 2, 'time': '30 min', 'v2': False, 'ai': False,
        'title_fr': 'Pierre-feuille-ciseaux', 'title_en': 'Rock-paper-scissors', 'title_ar': 'حجر ورقة مقص',
        'official': False,
        'objectif_fr': "Joue à pierre-feuille-ciseaux contre ton micro:bit. Tu secoues pour faire ton choix, le micro:bit révèle le sien et le résultat.",
        'materiel': ['micro:bit'],
        'etapes_fr': [
            "Bouton A = Pierre, B = Feuille, A+B = Ciseaux",
            "Au choix de l'humain : le micro:bit tire aléatoirement",
            "Afficher son choix puis comparer",
            "Montrer le résultat : W/L/=",
        ],
        'tip_fr': "Règles : Pierre > Ciseaux > Feuille > Pierre. Sinon : égalité.",
        'js': "function play(human: number) {\n    let bot = Math.randomRange(0, 2)\n    let icons = [IconNames.Square, IconNames.House, IconNames.Scissors]\n    basic.showIcon(icons[bot])\n    basic.pause(800)\n    if (human == bot) basic.showString(\"=\")\n    else if ((human == 0 && bot == 2) || (human == 1 && bot == 0) || (human == 2 && bot == 1)) basic.showString(\"W\")\n    else basic.showString(\"L\")\n}\ninput.onButtonPressed(Button.A, () => play(0))     // pierre\ninput.onButtonPressed(Button.B, () => play(1))     // feuille\ninput.onButtonPressed(Button.AB, () => play(2))    // ciseaux",
        'py': "from random import randint\n\ndef play(human):\n    bot = randint(0, 2)\n    icons = [IconNames.SQUARE, IconNames.HOUSE, IconNames.SCISSORS]\n    basic.show_icon(icons[bot])\n    basic.pause(800)\n    if human == bot:\n        basic.show_string(\"=\")\n    elif (human == 0 and bot == 2) or (human == 1 and bot == 0) or (human == 2 and bot == 1):\n        basic.show_string(\"W\")\n    else:\n        basic.show_string(\"L\")\n\ninput.on_button_pressed(Button.A, lambda: play(0))\ninput.on_button_pressed(Button.B, lambda: play(1))\ninput.on_button_pressed(Button.AB, lambda: play(2))",
        'defis_fr': [
            {'level': 'easy', 'text': "Garde le score des victoires et le montre avec le bouton logo"},
            {'level': 'med',  'text': "Joue le meilleur de 5 parties"},
        ],
    },
    {
        'id': 43, 'cat': 'interact', 'stars': 3, 'time': '40 min', 'v2': False, 'ai': False,
        'title_fr': 'Simon dit (mémoire)', 'title_en': 'Simon says', 'title_ar': 'قال سيمون',
        'official': False,
        'objectif_fr': "Le micro:bit montre une séquence de flèches (↑↓←→). Tu dois la répéter en appuyant dans le même ordre. Une flèche de plus à chaque tour.",
        'materiel': ['micro:bit'],
        'etapes_fr': [
            "Démarrer avec 1 flèche aléatoire dans la séquence",
            "Montrer la séquence (flèche + son)",
            "L'utilisateur appuie : A = gauche, B = droite, shake = haut, tilt forward = bas",
            "Si correct : ajouter 1 flèche. Sinon : game over + score",
        ],
        'tip_fr': "Plus la séquence grandit, plus c'est dur. Niveau 10 = exploit !",
        'js': "let seq: number[] = []\nlet playerIdx = 0\nlet waiting = false\nfunction showSequence() {\n    waiting = false\n    for (let step of seq) {\n        let icons = [ArrowNames.North, ArrowNames.South, ArrowNames.West, ArrowNames.East]\n        basic.showArrow(icons[step])\n        music.playTone(400 + step * 100, 200)\n        basic.clearScreen()\n        basic.pause(200)\n    }\n    playerIdx = 0\n    waiting = true\n}\nfunction input_step(s: number) {\n    if (!waiting) return\n    if (s == seq[playerIdx]) {\n        playerIdx++\n        music.playTone(600, 80)\n        if (playerIdx >= seq.length) {\n            basic.showIcon(IconNames.Happy)\n            basic.pause(400)\n            seq.push(Math.randomRange(0, 3))\n            basic.pause(500)\n            showSequence()\n        }\n    } else {\n        basic.showIcon(IconNames.Sad)\n        basic.showNumber(seq.length - 1)\n        seq = []\n        waiting = false\n    }\n}\ninput.onButtonPressed(Button.A, () => input_step(2))\ninput.onButtonPressed(Button.B, () => input_step(3))\ninput.onGesture(Gesture.Shake, () => input_step(0))\ninput.onGesture(Gesture.LogoDown, () => input_step(1))\ninput.onButtonPressed(Button.AB, function () { seq = [Math.randomRange(0, 3)]; showSequence() })",
        'py': "# Version JS recommandée (meilleur support des gestures)\nfrom random import randint\nseq = []\nplayer_idx = 0\nwaiting = False\n\ndef show_sequence():\n    global waiting, player_idx\n    waiting = False\n    for step in seq:\n        icons = [ArrowNames.NORTH, ArrowNames.SOUTH, ArrowNames.WEST, ArrowNames.EAST]\n        basic.show_arrow(icons[step])\n        music.play_tone(400 + step * 100, 200)\n        basic.clear_screen()\n        basic.pause(200)\n    player_idx = 0\n    waiting = True\n\ndef input_step(s):\n    global player_idx, seq, waiting\n    if not waiting: return\n    if s == seq[player_idx]:\n        player_idx += 1\n        music.play_tone(600, 80)\n        if player_idx >= len(seq):\n            basic.show_icon(IconNames.HAPPY)\n            basic.pause(400)\n            seq.append(randint(0, 3))\n            basic.pause(500)\n            show_sequence()\n    else:\n        basic.show_icon(IconNames.SAD)\n        basic.show_number(len(seq) - 1)\n        seq = []\n        waiting = False\n\ninput.on_button_pressed(Button.A, lambda: input_step(2))\ninput.on_button_pressed(Button.B, lambda: input_step(3))\ninput.on_gesture(Gesture.SHAKE, lambda: input_step(0))\ninput.on_gesture(Gesture.LOGO_DOWN, lambda: input_step(1))",
        'defis_fr': [
            {'level': 'easy', 'text': "Ajoute une couleur RGB différente par direction"},
            {'level': 'hard', 'text': "Enregistre le record et affiche-le au démarrage"},
        ],
    },
    {
        'id': 44, 'cat': 'interact', 'stars': 2, 'time': '20 min', 'v2': True, 'ai': False,
        'title_fr': 'Claps détection', 'title_en': 'Clap detector', 'title_ar': 'كاشف التصفيق',
        'official': False,
        'objectif_fr': "Le robot réagit au nombre de claps : 1 clap = LEDs rouges, 2 claps = LEDs vertes, 3 claps = danse !",
        'materiel': ['micro:bit V2 (micro intégré)', 'Maqueen Lite'],
        'etapes_fr': [
            "Écouter l'événement Loud (son fort)",
            "Compter les claps dans une fenêtre de 2 secondes",
            "Selon le total, déclencher une action différente",
        ],
        'tip_fr': "Le micro:bit v2 a un événement loud qui se déclenche sur les pics sonores.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\nlet claps = 0\nlet lastClapTime = 0\ninput.onSound(DetectedSound.Loud, function () {\n    let now = input.runningTime()\n    if (now - lastClapTime > 2000) claps = 1\n    else claps++\n    lastClapTime = now\n    basic.pause(300)\n    if (claps == 1) { strip.showColor(neopixel.colors(NeoPixelColors.Red)) }\n    else if (claps == 2) { strip.showColor(neopixel.colors(NeoPixelColors.Green)) }\n    else if (claps >= 3) {\n        strip.showColor(neopixel.colors(NeoPixelColors.Blue))\n        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n        basic.pause(1000)\n        maqueen.motorStop(maqueen.Motors.All)\n    }\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\nclaps = 0\nlast_clap_time = 0\n\ndef on_loud():\n    global claps, last_clap_time\n    now = input.running_time()\n    if now - last_clap_time > 2000:\n        claps = 1\n    else:\n        claps += 1\n    last_clap_time = now\n    basic.pause(300)\n    if claps == 1:\n        strip.show_color(neopixel.colors(NeoPixelColors.RED))\n    elif claps == 2:\n        strip.show_color(neopixel.colors(NeoPixelColors.GREEN))\n    elif claps >= 3:\n        strip.show_color(neopixel.colors(NeoPixelColors.BLUE))\n        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 150)\n        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 150)\n        basic.pause(1000)\n        maqueen.motor_stop(maqueen.Motors.ALL)\n\ninput.on_sound(DetectedSound.LOUD, on_loud)",
        'defis_fr': [
            {'level': 'easy', 'text': "4 claps = le robot fait un tour complet sur lui-même"},
            {'level': 'med',  'text': "Clap pour allumer, re-clap pour éteindre (télécommande sans les mains)"},
        ],
    },
    {
        'id': 45, 'cat': 'interact', 'stars': 2, 'time': '25 min', 'v2': False, 'ai': False,
        'title_fr': 'Roulette russe (jeu safe)', 'title_en': 'Safe roulette game', 'title_ar': 'لعبة الحظ الآمنة',
        'official': False,
        'objectif_fr': "Passe le micro:bit d'un joueur à l'autre. Si tu secoues et qu'une lumière rouge s'allume, tu as perdu ! Seul le hasard décide.",
        'materiel': ['micro:bit', 'Maqueen Lite'],
        'etapes_fr': [
            "Au Shake : tirer un nombre aléatoire 1-6",
            "Si 1 : afficher X + sirène + LEDs rouges → tu as perdu",
            "Sinon : afficher ✓ + son doux + LEDs vertes → tu passes au suivant",
        ],
        'tip_fr': "Jeu de passage idéal en groupe : personne ne sait qui sera le perdant.",
        'js': "let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)\ninput.onGesture(Gesture.Shake, function () {\n    basic.showIcon(IconNames.Heart)\n    basic.pause(800)\n    let roll = Math.randomRange(1, 6)\n    if (roll == 1) {\n        for (let i = 0; i < 6; i++) {\n            strip.showColor(neopixel.colors(NeoPixelColors.Red))\n            music.playTone(880, 100)\n            strip.clear()\n    strip.show()\n            basic.pause(80)\n        }\n        basic.showIcon(IconNames.Skull)\n    } else {\n        strip.showColor(neopixel.colors(NeoPixelColors.Green))\n        music.playTone(660, 200)\n        basic.showIcon(IconNames.Yes)\n    }\n})",
        'py': "strip = neopixel.create(DigitalPin.P15, 4, neopixel.NeoPixelMode.RGB)\nfrom random import randint\n\ndef on_shake():\n    basic.show_icon(IconNames.HEART)\n    basic.pause(800)\n    roll = randint(1, 6)\n    if roll == 1:\n        for i in range(6):\n            strip.show_color(neopixel.colors(NeoPixelColors.RED))\n            music.play_tone(880, 100)\n            strip.clear()\n    strip.show()\n            basic.pause(80)\n        basic.show_icon(IconNames.SKULL)\n    else:\n        strip.show_color(neopixel.colors(NeoPixelColors.GREEN))\n        music.play_tone(660, 200)\n        basic.show_icon(IconNames.YES)\n\ninput.on_gesture(Gesture.SHAKE, on_shake)",
        'defis_fr': [
            {'level': 'easy', 'text': "Augmente la difficulté : 2 chances sur 6 de perdre"},
            {'level': 'med',  'text': "Mode « tournoi » : compte les pertes de chaque joueur avec 3 micro:bits"},
        ],
    },
]

print(f"PHASE2 defined: {len(PHASE2)} activities")
