"""Phase 4: Learning paths (parcours). 6 curated sequences through the activities.
Each path is a dict with: id, icon, name_fr/en/ar, desc_fr/en/ar, age_fr/en/ar, duration_fr/en/ar, activity_ids."""

PARCOURS = [
    {
        'id': 'debutant',
        'icon': '🐣',
        'name_fr': 'Parcours débutant (8-10 ans)',
        'name_en': 'Beginner path (8-10 years)',
        'name_ar': 'مسار المبتدئين (8-10 سنوات)',
        'desc_fr': "Premier contact avec la robotique. Allumer des LEDs, faire bouger le robot, comprendre les bases. 10 activités en douceur, ~2h au total.",
        'desc_en': "First steps with robotics. Turn on LEDs, make the robot move, grasp the basics. 10 gentle activities, ~2h total.",
        'desc_ar': "أول لقاء مع الروبوتات. إضاءة المصابيح، تحريك الروبوت، فهم الأساسيات. 10 أنشطة هادئة، ~ساعتان إجمالاً.",
        'age_fr': '8-10 ans', 'age_en': '8-10 years', 'age_ar': '8-10 سنوات',
        'duration_fr': '~2h', 'duration_en': '~2h', 'duration_ar': '~ساعتان',
        'activity_ids': [1, 2, 3, 4, 5, 17, 24, 25, 31, 32],
    },
    {
        'id': 'junior',
        'icon': '🎓',
        'name_fr': 'Parcours junior (10-12 ans)',
        'name_en': 'Junior path (10-12 years)',
        'name_ar': 'مسار الابتدائي (10-12 سنة)',
        'desc_fr': "Niveau scolaire primaire-collège. Les capteurs, les boucles, le suivi de ligne, les jeux avec le robot. 12 activités, ~4h.",
        'desc_en': "Elementary to middle-school level. Sensors, loops, line following, games with the robot. 12 activities, ~4h.",
        'desc_ar': "مستوى المرحلة الابتدائية والإعدادية. المستشعرات، الحلقات، متابعة الخط، ألعاب مع الروبوت. 12 نشاطاً، ~4 ساعات.",
        'age_fr': '10-12 ans', 'age_en': '10-12 years', 'age_ar': '10-12 سنة',
        'duration_fr': '~4h', 'duration_en': '~4h', 'duration_ar': '~4 ساعات',
        'activity_ids': [6, 7, 8, 12, 13, 33, 34, 40, 41, 49, 54, 55],
    },
    {
        'id': 'ado',
        'icon': '🚀',
        'name_fr': 'Parcours adolescent (12-15 ans)',
        'name_en': 'Teen path (12-15 years)',
        'name_ar': 'مسار المراهقين (12-15 سنة)',
        'desc_fr': "Pour collégiens motivés. Programmation avancée, communication radio, défis de compétition. 12 activités, ~8h de travail.",
        'desc_en': "For motivated middle-schoolers. Advanced programming, radio communication, competition challenges. 12 activities, ~8h of work.",
        'desc_ar': "لطلاب الإعدادية المتحمسين. برمجة متقدمة، اتصال لاسلكي، تحديات تنافسية. 12 نشاطاً، ~8 ساعات من العمل.",
        'age_fr': '12-15 ans', 'age_en': '12-15 years', 'age_ar': '12-15 سنة',
        'duration_fr': '~8h', 'duration_en': '~8h', 'duration_ar': '~8 ساعات',
        'activity_ids': [9, 10, 11, 14, 15, 46, 47, 50, 58, 59, 63, 73],
    },
    {
        'id': 'ia',
        'icon': '🧠',
        'name_fr': "Parcours IA — Intelligence artificielle",
        'name_en': 'AI path — Artificial Intelligence',
        'name_ar': 'مسار الذكاء الاصطناعي',
        'desc_fr': "De CreateAI à Teachable Machine. Entraîner des modèles, les déployer sur le micro:bit, comprendre l'apprentissage automatique. 10 activités.",
        'desc_en': "From CreateAI to Teachable Machine. Train models, deploy them on the micro:bit, understand machine learning. 10 activities.",
        'desc_ar': "من CreateAI إلى Teachable Machine. تدريب النماذج، نشرها على micro:bit، فهم التعلم الآلي. 10 أنشطة.",
        'age_fr': '12+ ans', 'age_en': '12+ years', 'age_ar': '12+ سنة',
        'duration_fr': '~6h', 'duration_en': '~6h', 'duration_ar': '~6 ساعات',
        'activity_ids': [74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
    },
    {
        'id': 'competition',
        'icon': '🏆',
        'name_fr': 'Parcours compétition',
        'name_en': 'Competition path',
        'name_ar': 'مسار المسابقة',
        'desc_fr': "Préparer un robot pour une compétition : suivi de ligne optimisé, sumo, évitement d'obstacles, course chronométrée. 8 activités intensives.",
        'desc_en': "Prepare a robot for competition: optimized line following, sumo, obstacle avoidance, timed race. 8 intensive activities.",
        'desc_ar': "إعداد روبوت للمسابقة: متابعة خط محسّنة، سومو، تجنب العقبات، سباق موقوت. 8 أنشطة مكثفة.",
        'age_fr': '11+ ans', 'age_en': '11+ years', 'age_ar': '11+ سنة',
        'duration_fr': '~5h', 'duration_en': '~5h', 'duration_ar': '~5 ساعات',
        'activity_ids': [11, 12, 46, 47, 50, 51, 57, 72],
    },
    {
        'id': 'creatif',
        'icon': '🎨',
        'name_fr': 'Parcours créatif',
        'name_en': 'Creative path',
        'name_ar': 'المسار الإبداعي',
        'desc_fr': "Le robot comme outil d'expression artistique : dessinateur, danseur, musicien, conteur. 8 activités pour artistes en herbe.",
        'desc_en': "The robot as an artistic expression tool: drawer, dancer, musician, storyteller. 8 activities for budding artists.",
        'desc_ar': "الروبوت كأداة للتعبير الفني: رسّام، راقص، موسيقي، حكواتي. 8 أنشطة للفنانين الناشئين.",
        'age_fr': '9+ ans', 'age_en': '9+ years', 'age_ar': '9+ سنة',
        'duration_fr': '~5h', 'duration_en': '~5h', 'duration_ar': '~5 ساعات',
        'activity_ids': [3, 5, 24, 25, 26, 29, 48, 55],
    },
]

print(f"Phase 4: {len(PARCOURS)} learning paths (trilingual)")
